name = "Zenarchist's Time Bomb"; // name
picture = ""; // picture in expanded description
logoSmall = ""; // icon next to mod name when description is not expanded
logo = ""; // logo below game menu
logoOver = ""; // on mouse hover over logo
tooltip = "Zenarchist's Time Bomb"; // tool tip on mouse hover
overview = "Adds a the ability to attach grenades to alarm clocks to make traps."; // overview
action = "https://zenarchist.io/"; // link
author = "Zenarchist"; // author
version = "1.0"; // version